# Generated by Django 2.2.7 on 2020-01-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewTasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='comments',
        ),
        migrations.AddField(
            model_name='taskitem',
            name='comment',
            field=models.TextField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='title',
            field=models.TextField(default='', max_length=50),
        ),
    ]
