# Generated by Django 2.2.7 on 2020-01-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewTasks', '0002_auto_20200109_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='comment',
            field=models.TextField(default='comment', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='due_date',
            field=models.DateField(default='2020-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='star',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='title',
            field=models.TextField(default='title', max_length=100, null=True),
        ),
    ]
